#!/usr/bin/python

import glob
import os
import subprocess
import sys
import stat

files = glob.glob("Assets/Editor/PostprocessBuildPlayer_*")
for filename in files:
    callcmd = [filename] + sys.argv[1:]
    try:
        # Make sure sub-script is executable.
        st = os.stat(filename)
        os.chmod(filename, st.st_mode | stat.S_IEXEC)
        os.system(" ".join(callcmd))
        #result = subprocess.call(callcmd, stderr=None, shell=True)
    except:
        sys.exit