#!/usr/bin/python
import os
#from Cocoa import NSDictionary
import sys
import re
from distutils import dir_util

import PbxprojHZ

try:
  for proj in os.listdir(sys.argv[1]):
    if not re.search('\.xcodeproj', proj):
      continue

    proj = os.path.join(sys.argv[1], proj)
    pb = PbxprojHZ.PbxprojHZ(proj)

    # Add the Frameworks
    pb.add_framework("AdSupport.framework", True) #weak-linked
    pb.add_framework("StoreKit.framework", True) #weak-linked
    pb.add_framework("CoreGraphics.framework")
    pb.add_framework("QuartzCore.framework")
    pb.add_framework("CoreTelephony.framework")
    
except:
  e = sys.exc_info()[0]